all: ansible

ROLE = all

_roles: roles.yml
	ansible-galaxy install -r roles.yml

all.yml: script/make-all-playbook.py lib/make_all_playbook.py
	ENV=$(ENV) python script/make-all-playbook.py

ansible: _roles all.yml
	ENV=$(ENV) ansible-playbook -i $(ENV).yml -i inventories \
		$(ROLE).yml --diff

test: _roles all.yml
	ENV=$(ENV) ansible-playbook -i $(ENV).yml -i inventories \
		--syntax-check $(ROLE).yml
