all: ansible

ROLE = all

_roles: roles.yml
	ansible-galaxy install -r roles.yml

playbooks/all.yml: script/make-all-playbook.py lib/make_all_playbook.py
	ENV=$(ENV) python script/make-all-playbook.py

ansible: _roles playbooks/all.yml
	ENV=$(ENV) ansible-playbook -i $(ENV).yml -i inventories \
		playbooks/$(ROLE).yml

test: _roles playbooks/all.yml
	ENV=$(ENV) ansible-playbook -i $(ENV).yml -i inventories \
		--syntax-check playbooks/$(ROLE).yml
