#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os

import yaml

from inventory import read_cfg, normalize_servers, read_data


class AllPlaybook(object):

    def get_dest_path(self):
        return os.path.abspath(os.path.join(
            os.path.dirname(__file__), "..", "playbooks", "all.yml"))

    def conv_data(self, data):
        return [
            {"import_playbook": "{}.yml".format(group_name)}
            for env, env_data in data.items() for group_name in env_data["groups"]]

    def run(self):
        cfg = read_cfg()
        data = normalize_servers(read_data(cfg))
        with open(self.get_dest_path(), "w") as w:
            w.write(
                "# playbooks/all.yml\n"
                "# Don't edit this file directly.\n"
                "# This file is generated by make-all-playbook command.\n"
                "# This file should be included in .gitignore.\n")
            yaml.dump(self.conv_data(data), w)
